### PR TITLE
feat!: new generated version of compute API

### PR DESCRIPTION
**Pull request by alexander-fenster**
Generator: gapic-generator-typescript version: 2.2.0

**Break Change**
As we discuss in the email thread, we remove hand written features and will provide sample code.

**Additional features:**
- Support Pagination for compute where it is not-AIP compliant
- Detect transports
- REST-encode requests
- Default value
- Pass auth in HTTP headers
etc.

CLI command to generate nodejs-compute local:
```
$ bazel run //:gapic_generator_typescript -- -I $GOOGLEAPIS_DISCOVERY --output-dir /tmp/output $GOOGLEAPIS_DISCOVERY/google/cloud/compute/v1/compute.proto --package-name @google-cloud/compute --diregapic
```

Next: Update Bazel file to support auto-generation [PR](https://github.com/googleapis/googleapis-discovery/pull/56)
Once it done, it is available using:
`bazel build //google/cloud/compute/v1:compute-v1-nodejs`

### CODE REVIEW

**Comment by roikoren755** [comment]
Picking up on the conversation from #534 -
I'm trying to run the equivalent of `await new Compute().getVMs({ filter: 'some filter' })` from v2.
Trying the following code results in an error:

```
const client = new v1.InstancesClient();
const [instancesList] = await client.list({ filter: 'some string' }); // client.aggregatedList gives the same error...
```

The error is `13 INTERNAL: Received RST_STREAM with code 0`. If I add `{ fallback: true }` as parameter for the client constructor, the error changes to `invalid wire type 4 at offset 1`.

**Comment by MHDante** [comment]
Hi, @bcoe.  When trying to use the `3.0.0-alpha.1` release, I ran into what looks like a proto file mismatch. 

The following code:

```
import compute = require('@google-cloud/compute');


async function main(){
var instancesClient = new compute.InstancesClient({fallback: true}); 

const [list] = await instancesClient.list({})
console.log(list)

}

main().catch(e=> console.error(e))
```

yields the following error:

```

Error: invalid wire type 4 at offset 1
    at Reader.skipType (C:\Repos\pdp-deploy\node_modules\protobufjs\src\reader.js:377:19)
    at Type.Status$decode [as decode] (eval at Codegen (C:\Repos\pdp-deploy\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:22:5)     
    at Type.decode_setup [as decode] (C:\Repos\pdp-deploy\node_modules\protobufjs\src\type.js:507:25)
    at FallbackErrorDecoder.decodeRpcStatus (C:\Repos\pdp-deploy\node_modules\google-gax\src\fallbackError.ts:70:37)
    at FallbackErrorDecoder.decodeErrorFromBuffer (C:\Repos\pdp-deploy\node_modules\google-gax\src\fallbackError.ts:92:42)
    at C:\Repos\pdp-deploy\node_modules\google-gax\src\fallback.ts:439:45
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```


Is this path (automated generation of client libraries) still the path forward for your team? If so, let me know, and I'd be happy to give more feedback on iterations of 3.0.0.

**Comment by MHDante** [comment]
I have 2 pieces of feedback at the moment. 

1)

I think that the typing for the `fallback` field inside `ClientOptions` is limited to `boolean | undefined`. Whereas the documentation indicates passing in a `'rest'` string. Adding this (and a handy `// @ts-ignore` solves this issue, however, updating the typing would be preferable.

2) 

Failure messages that occur when passing in an incomplete object as a request into a method are not very informational.

This line failed:
`const [list] = await instancesClient.list({})`
despite the fact that all of the fields in `IListInstancesRequest` are optional.

I got the message: 
`Error: Cannot build HTTP request for {}, method: List`

My assumption is that it would use the default project and zone, but I then added the project and region as per the documentation. While this is on me for not RTFM, It would be useful for the error to display the required fields.

Thank you for your effort!

**Comment by alexander-fenster** [comment]
Hi @MHDante,

Thank you for your comments, and sorry for not getting back to you earlier. Yes, we are going to drive this all the way to completion :)  As for your points - the `fallback` export is fixed and now accepts `rest` (but the final code will not require this to be set and will choose between gRPC and REST automatically for the given library).  As for the empty request, I believe all requests must have `project` and `region` field; the fact that they are marked as optional in the interface is the specifics of protobuf.js, the third party protobuf library we use (we may probably fix it by the official release but it will stay this way for the time being).

I'm going to make a few more minor fixes later this week and will then release it as 3.0.0-alpha.2. After that we'll see if we could save any of the existing helper code to improve the experience for the auto-generated library.

Please follow this PR for more updates. Thank you!

**Comment by bcoe** [comment]
@MHDante, @roikoren755 apologies for missing these messages, as @alexander-fenster says we're working hard to get this over the finish line, we should have updates landing soon (including new samples).

**Pull request merged**
