### PR TITLE
Accept baseUrl in client options.

### PR DESCRIPTION
**Pull request by toots**
This allows the client to use the `beta` API.

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Thank you for sending this. I'm not sure if this is behavior we want to open up. @JustinBeckwith @crwilcox @callmehiphop ?

For now, you can use request interceptors:

```js
const Compute = require('@google-cloud/compute')
const compute = new Compute()

compute.interceptors.push({
  request: (reqOpts) => {
    reqOpts.uri = reqOpts.uri.replace('/v1/', '/beta/')
    return reqOpts
  }
})
```

**Comment by toots** [comment]
That's great, thank you!

**Comment by fhinkel** [comment]
Looks like using interceptors works for you. Feel free to reopen if needed.

**Comment by toots** [comment]
Yes it does indeed, sorry I forgot to close it. Thks!

**Pull request closed without merging**
