### PR TITLE
refactor: migrate to TypeScript

### LINKED ISSUE #495: Missing typescript declaration file
#### Environment details

  - OS: Linux
  - npm version: latest
  - `@google-cloud/compute` version: 2.1.0

#### Steps to reproduce

  1. Install it with npm/yarn
  2. Try to use it from typescript with `import Compute from '@google-cloud/compute`
  3. See errors re: missing typescript declaration

It seems this lib is missing a `.d.ts` typescript decl file, and I was unable to find typings on definitely-typed either. If this is intended to be the idiomatic way to interact with the compute API, I think typings would be very helpful.

### PR DESCRIPTION
**Pull request by roikoren755**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-compute/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #495 🦕

### CODE REVIEW

**Comment by roikoren755** [comment]
@googlebot I signed it!

**Comment by roikoren755** [comment]
There are still a few issues I need to resolve, namely a few `// @ts-ignore` comments I inserted to remind me of type mismatches. Hoping to get those out of the way soon

**Comment by roikoren755** [comment]
Regarding the failing checks - 
* There's still one error in ESLint, which I'm not sure how to solve. In the `Compute` class, in the constructor, the library's `package.json` is required and saved to a field. Since the library in now transpiled, the output is placed inside a build dir. The `package.json` file isn't moved, and so cannot be found when requiring `'../package.json'`, instead needing to require it from `'../../package.json'`, as was done in `@google-cloud/storage`. Not sure how to resolve this issue.
* Not sure how to fix the `header-check` check, tried changing the license header in the files it errors on, could not get it to work.
* And finally, code coverage - I created an `interfaces.ts` file that isn't tested at all, moved the old `index.js` to `compute.ts`, and created a new `index.ts` file that exports everything, without holding any code. This file, likewise, is not tested. This lowers the coverage, unfortunately. Not sure about other files, where interfaces and function overload signatures were added.

**Comment by bcoe** [comment]
@roikoren755 appreciate the PR 👍 

It might be a little while before we can give a thorough review. There has been some work internally to potentially auto-generate compute, in the not-too-distant future as well (_which would generate it with types_).

I'd like to figure out where this work stands.

**Comment by oveddan** [comment]
Thanks for working on this PR!  I hope typescript is supported soon in this sdk, it would make things much easier.

**Comment by bcoe** [comment]
@roikoren755 before we dive into the review of this PR, I was wondering if you might be able to take a look at the TypeScript support we're planning for the next major version:

https://github.com/googleapis/nodejs-compute/pull/537

Installable here:

https://www.npmjs.com/package/@google-cloud/compute/v/3.0.0-alpha.1

---

I discussed this PR with my peers this week, we're open to landing this functionality. But, we think we're potentially only a few weeks out on landing #537, which moves us from a handwritten library with out TypeScript types, to an automatically generated library with TypeScript types.

**Comment by roikoren755** [comment]
> @roikoren755 before we dive into the review of this PR, I was wondering if you might be able to take a look at the TypeScript support we're planning for the next major version:
> 
> https://github.com/googleapis/nodejs-compute/pull/537
> 
> Installable here:
> 
> https://www.npmjs.com/package/@google-cloud/compute/v/3.0.0-alpha.1
> 
> ---
> 
> I discussed this PR with my peers this week, we're open to landing this functionality. But, we think we're potentially only a few weeks out on landing #537, which moves us from a handwritten library with out TypeScript types, to an automatically generated library with TypeScript types.

I can take a look at it over the weekend. What exactly would you like me to check? The use case we have in my company is a fairly simple one

**Comment by bcoe** [comment]
> What exactly would you like me to check? The use case we have in my company is a fairly simple one

@roikoren755  perhaps you could see if the new generated library meets your company's needs, in which case perhaps we could support you in using it (or fix issues based on your feedback).

**Comment by jasonswearingen** [comment]
> 
> 
> > What exactly would you like me to check? The use case we have in my company is a fairly simple one
> 
> @roikoren755 perhaps you could see if the new generated library meets your company's needs, in which case perhaps we could support you in using it (or fix issues based on your feedback).

I tried using ```3.0.0-alpha.1```....   it looks like it will be fine if you add some better samples.  The samples included in the readme.md are too trivial to explain the patterns the new api designs expect, and there seems to be no other documentation included.   (All other docs looks to refer to the previous api)

Also, How can I access the compute Beta API ?

**Comment by SurferJeffAtGoogle** [comment]
This PR has been inactive for 3+ months.

**Pull request closed without merging**
