### PR TITLE
Adds basic support for InstanceGroupManager

### PR DESCRIPTION
**Pull request by modeswitch**
- Basic instance support (exists, get, getMetadata, etc).
- Supports resize as well.
- Partially addresses #103.

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by modeswitch** [comment]
This is ready to be reviewed now. I don't know how to check the status on the automated checks.

**Comment by JustinBeckwith** [comment]
This is awesome!

**Comment by modeswitch** [comment]
@JustinBeckwith I think the code coverage should be back up on `zone.js`. I'm not sure why the docs links are broken though.

**Comment by modeswitch** [comment]
Can I run the ci/kokoro tests locally?

**Comment by modeswitch** [comment]
@JustinBeckwith Docs added for `InstanceGroupManager`. I think that should fix the last of the CI complaints. Can you re-run kokoro?

**Comment by JustinBeckwith** [comment]
Thanks for being patient with this one :)

**Comment by modeswitch** [comment]
Heh, 3 hours on a Sunday is tolerable :P

**Comment by toots** [comment]
Awesome, thanks for the work!

**Pull request merged**
