### PR TITLE
fix: snapshot.delete() throws issue

### LINKED ISSUE #250: Bug: snapshot.delete() throws
When using `snapshot.delete()`, it should return a promise which will resolve an array contains an operation object.

But it just throws an error, said: "TypeError: Cannot read property 'operation' of undefined
    at /workspace/node_modules/@google-cloud/compute/src/snapshot.js:223:33".

After some debugging, I found out, at [snapshot.js:223:33](https://github.com/googleapis/nodejs-compute/blob/a089112b687b6c9759a5bd945732c1d398908f58/src/snapshot.js#L223), the `compute` variable is undefined because when constructing snapshot object, it will use `scope`, which has no `compute` field.

image

Using `scope.parent.compute` or `scope.zone.compute` will solve this problem.

I'll send a PR later.
#### Environment details

  - OS: Linux(Fedora 29), kernel: 4.19.13-300.fc29.x86_64
  - Node.js version: v10.15.0
  - npm version: 6.4.1
  - `@google-cloud/compute` version: 0.11.0

#### Steps to reproduce

```
const disk = compute.zone(zone).disk(diskName)
const snapshot = disk.snapshot(snapshotName)
const [operation] = await snapshot.delete() // throws here
```

### PR DESCRIPTION
**Pull request by chux0519**
also modified the related test case

Fixes #250 

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Thank you! I added a line in our system tests to back up the test as well.

**Comment by stephenplusplus** [comment]
@JustinBeckwith the robots are fighting me on this one :)

**Comment by kinwa91** [comment]
run `npm run fix` to make `lint` run :)

**Comment by stephenplusplus** [comment]
Thank you, @chux0519!

**Pull request merged**
