### PR TITLE
Normalize arguments when using new.

### PR DESCRIPTION
**Pull request by stephenplusplus**
Related: https://github.com/googleapis/nodejs-pubsub/issues/38

### CODE REVIEW

**Comment by stephenplusplus** [comment]
@alexander-fenster could we un-require the docs and lint task?

**Comment by alexander-fenster** [comment]
The problem here was not with docs and lint, but with node6 test that failed. The same happened for node4 test in #38. Looks like one of those tasks randomly times out.

**Comment by alexander-fenster** [comment]
As for lint, after I restarted the failed CI tasks, it found one error 
```
/root/project/test/index.js
  189:9  error  'options' is assigned a value but never used  no-unused-vars
```

I guess everything will be OK after this one is fixed.

**Comment by alexander-fenster** [comment]
Same linting error happens in #38. Is there anything wrong with that? Anyway, I don't think disabling lint is a good idea.

**Comment by stephenplusplus** [comment]
Woops, when I left the message, those tasks were stalling, I didn't even realize there was an actual issue. In fact, this PR is a copy of my last one, #38, where those tasks never ran and reported to GitHub.

So, fixed the lint issue. But, in general, I think *all* of these things should pass before we merge code into master. However, we have made some choices to not require them based on CI/GH integration issues. For example, Windows testing and snyk aren't required before merging.

As long as docs and lint report in a timely manner, I agree we should keep them. In my experience, those two tasks have always given problems, where everything else is green, but those stall out in a permanent "Waiting for status to be reported" state. Let's see how it goes after I pushed a fix for the lint issue.

**Comment by stephenplusplus** [comment]
@alexander-fenster ping :)

**Pull request merged**
