### PR TITLE
docs: fixes small typo

### PR DESCRIPTION
**Pull request by haraldreingruber**
It's just a small typo fix. Maybe this is helpful.

### CODE REVIEW

**Comment by haraldreingruber** [comment]
@googlebot I signed it!

**Review by JustinBeckwith — APPROVED** [review]

**Comment by tmatsuo** [comment]
It's not your fault, but this file has `[START gce_startup_script]`, but doesn't have matching `[END gce_startup_script]`.
I think you can add `[END gce_startup_script]` at the end of the function.
Can you add it?

Also, the conventional commit looks at the commit message of the first commit, not the title of the PR, so you may need to change the commit message. You can easily change the commit message with `git commit --amend` command.

**Comment by haraldreingruber** [comment]
@tmatsuo sure, no problem.
Let me know if that works for you?

**Comment by tmatsuo** [comment]
@haraldreingruber
Perfect! Thank you for the fix!

**Comment by tmatsuo** [comment]
The lint seems failing. Maybe I can push the change.

**Pull request merged**
